services:
  stock-ia-forecasting:
    build: .
    container_name: stock-ia-forecasting
    ports:
      - "8080:8080"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8080
      - HOST=0.0.0.0
      - DEBUG=False
    volumes:
      - .:/app
    working_dir: /app
    command: ["uv", "run", "main.py"]

